### PR TITLE
data cleaning

### PR DESCRIPTION
**Pull request by sharanya02**
# Pull Request Type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

# Purpose
- Cleaned the data and divided data into training and testing

# Does this PR introduce any new bug?
- [ ] Yes
- [x] No
- [ ] Maybe

### CODE REVIEW

**Comment by SaurusXI** [comment]
@sharanya02 good job on signing commits :)

**Review by SaurusXI — APPROVED** [review]
@sharanya02 also change the README subtitle in this PR and move that text to description

**Comment by sharanya02** [comment]
> @sharanya02 also change the README subtitle in this PR and move that text to description

Alright, will do that

**Comment by SaurusXI** [comment]
@sharanya02 push the readme change so i can merge this PR

**Comment by sharanya02** [comment]
> @sharanya02 push the readme change so i can merge this PR

done.

**Pull request merged**
